Create sum-bits.bril
sampsyo/bril pull request #67
Opened 2020-09-14 16:53 UTC by stp59

A small bril program which counts the number of ones in the bit-representation of a given integer.

2020-09-14 17:40 UTC, sampsyo requested changes
Neat; looks cool! Please remember to add the test output files.

2020-09-14 17:40 UTC, sampsyo commented on docs/tools/bench.md
> +* `sum-bit`: Print the number of bits in the binary representation of the input integer
```suggestion
* `sum-bit`: Print the number of bits in the binary representation of the input integer.
```

2020-09-14 20:59 UTC, stp59 commented
I think this should do it!

2020-09-14 21:04 UTC, sampsyo reviewed
Looking good! One suggestion for the wording inside. Would you also mind resolving the conflicts? Thanks!!

2020-09-14 21:04 UTC, sampsyo commented on docs/tools/bench.md
> +* `sum-bit`: Print the number of bits in the binary representation of the input integer.
Maybe this should be "the number of 1 bits"? It's not the totally length of the binary representation (i.e., the position of the highest 1).

2020-09-17 23:59 UTC, stp59 commented
Sorry I just now saw this. Conflicts resolved!

2020-09-18 11:52 UTC, sampsyo approved these changes
Great; thanks!

2020-09-18 11:52 UTC, merged